name: Run Next App

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: install modules
        run: npm i
      - name: Linting
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
